# Introduction to OOP(object Oriented Programming)

In [2]:
def test():
    print('test() for the class and method')
    return
test()
    

test() for the class and method


In [5]:
class demo:
    def test(self):
        print('test() for the class and method')
        return
obj=demo()
obj.test()

test() for the class and method


In [1]:
class demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=demo1()
print(p1.fact(5))


120


In [86]:
class demo2:

    def __init__(self,p1,p2):
        self.p1=p2
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
    
c1=demo2(10,20)
print(c1.add(100,200))

300


In [87]:
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
class employee(person):
    def isemployee(self):
        return True
emp=person("Anil")
print(emp.getname(),emp.isemployee())
emp1=employee("Akhil")
print(emp1.getname(),emp1.isemployee())

Anil False
Akhil True


# Python Numpy
1.it is like list in python


In [88]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [89]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [90]:
lst=[1,2,3,4]
array=np.array(lst)
print(array)
print(array.shape)
print(array.dtype)

[1 2 3 4]
(4,)
int32


In [91]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [93]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [94]:
a1=np.random.normal(5,0.5,10)
print(a1)

[4.37812117 5.64056202 5.13868404 4.77100167 6.0480817  5.56298358
 5.34941248 4.76558393 5.61924255 5.04640807]


In [95]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [96]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [97]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [98]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [100]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [101]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [102]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,1])

slicing column: [2 5]


In [103]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [104]:
a1=np.array([(1,2,3),(4,5,6)])
print("First Row:",a1[0])

First Row: [1 2 3]


In [105]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row:",a1[1])

second row: [4 5 6]


In [106]:

a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,1])

slicing column: [2 5]


In [107]:
a1=np.array([(1,2,3),(4,5,6)])
print("Row and Column:",a1[1:2])

Row and Column: [[4 5 6]]


In [108]:
a1=np.random.normal(5,0.5,10)
print(a1)
print("Min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[4.41557756 5.6390988  4.95155109 5.0318345  5.18438628 4.51855235
 4.24774416 5.22623793 4.7878817  4.8091651 ]
Min value= 4.247744158392547
max value= 5.639098795115728
mean value= 4.88120294464075
median value= 4.880358091333028


In [109]:
c1=np.array([1,2])
c2=np.array([3,4])
np.dot(c1,c2)

11

In [110]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

# Pandas Database

In [119]:
import pandas as py
dict={"Name":["Anil","Akhil","Harshit"],
     "Email ID":["anil.tej90123@gmail.com","akhil.tey92347@gmail.com","harshit.raj10a@gmail.com"],
      "Mobile no.":["9238485345","9847659023","8564936589"],
      "Address":["Hyd","Hyd","Hyd"]}
b=pd.DataFrame(dict)
print(b)   

      Name                  Email ID  Mobile no. Address
0     Anil   anil.tej90123@gmail.com  9238485345     Hyd
1    Akhil  akhil.tey92347@gmail.com  9847659023     Hyd
2  Harshit  harshit.raj10a@gmail.com  8564936589     Hyd


In [114]:
b.index=["01","02","03"]
print(b)

       Name                  Email ID  Mobile no. Address
01     Anil   anil.tej90123@gmail.com  9238485345     Hyd
02    Akhil  akhil.tey92347@gmail.com  9847659023     Hyd
03  Harshit  harshit.raj10a@gmail.com  8564936589     Hyd
